version: '3.7'

services:
  register_ingester:
    image: register_ingester:latest
    environment:
      - OPENCORPORATES_SFTP_HOST
      - OPENCORPORATES_SFTP_USER
      - OPENCORPORATES_SFTP_PASSWORD
      - BODS_S3_BUCKET_NAME
      - BODS_AWS_REGION
      - BODS_AWS_ACCESS_KEY_ID
      - BODS_AWS_SECRET_ACCESS_KEY
      - ATHENA_DATABASE
      - ATHENA_S3_BUCKET
      - COMPANIES_ATHENA_RAW_TABLE_NAME
      - COMPANIES_ATHENA_PROCESSED_TABLE_NAME
      - COMPANIES_ATHENA_FILTERED_TABLE_NAME
      - COMPANIES_BULK_DATA_S3_PREFIX
      - COMPANIES_PROCESSED_S3_LOCATION
      - COMPANIES_FILTERED_S3_LOCATION
      - COMPANIES_EXPORT_JSON_FULL_S3_PREFIX
      - COMPANIES_EXPORT_JSON_DIFFS_S3_PREFIX
      - ADD_IDS_ATHENA_RAW_TABLE_NAME
      - ADD_IDS_ATHENA_PROCESSED_TABLE_NAME
      - ADD_IDS_ATHENA_FILTERED_TABLE_NAME
      - ADD_IDS_BULK_DATA_S3_PREFIX
      - ADD_IDS_PROCESSED_S3_LOCATION
      - ADD_IDS_FILTERED_S3_LOCATION
      - ADD_IDS_EXPORT_JSON_FULL_S3_PREFIX
      - ADD_IDS_EXPORT_JSON_DIFFS_S3_PREFIX
      - ALT_NAMES_ATHENA_RAW_TABLE_NAME
      - ALT_NAMES_ATHENA_PROCESSED_TABLE_NAME
      - ALT_NAMES_ATHENA_FILTERED_TABLE_NAME
      - ALT_NAMES_BULK_DATA_S3_PREFIX
      - ALT_NAMES_PROCESSED_S3_LOCATION
      - ALT_NAMES_FILTERED_S3_LOCATION
      - ALT_NAMES_EXPORT_JSON_FULL_S3_PREFIX
      - ALT_NAMES_EXPORT_JSON_DIFFS_S3_PREFIX
      - ELASTICSEARCH_HOST
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_PROTOCOL
      - ELASTICSEARCH_SSL_VERIFY
      - ELASTICSEARCH_PASSWORD
      - OC_API_TOKEN
      - OC_API_TOKEN_PROTECTED
    volumes:
      - './storage:/storage'
    restart: always

  register_ingester_es_test:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - 'discovery.type=single-node'
      - 'cluster.name=register-elasticsearch'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'xpack.security.enabled=false'
    networks:
      - register_ingester_test
    expose:
      - 9200

  register_ingester_unittests:
    image: register_ingester:latest
    environment:
      - ELASTICSEARCH_HOST=register_ingester_es_test
      - ELASTICSEARCH_PASSWORD=
      - ELASTICSEARCH_PORT=9200
      - TEST=1
    links:
      - register_ingester_es_test
    networks:
      - register_ingester_test
    volumes:
      - '.:/app'

networks:
  register_ingester_test:
