version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0
    volumes:
      - 'es_ingester_data:/usr/share/elasticsearch/data'
    environment:
      - 'discovery.type=single-node'
      - 'cluster.name=register-elasticsearch'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - 9200:9200
    restart: always

volumes:
  es_ingester_data:
